development: &development
  adapter: postgresql
  reconnect: false
  pool: 10
  min_messages: WARNING
  database: web_observer_development

test: &test
  adapter: postgresql
  reconnect: false
  pool: 10
  min_messages: WARNING
  database: web_observer_test

production: &production
  adapter: postgresql
  reconnect: false
  pool: 10
  min_messages: WARNING
  database: web_observer_production
